apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booli-targets-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
  - host: target.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: booli-targets
            port:
              number: 80